name: Fetch latest data and deploy with Datasette

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check out unitedstates/congress-legislators
      uses: actions/checkout@v3
      with:
        repository: unitedstates/congress-legislators
        path: congress-legislators
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: pip
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build database
      run: |
        python build_database.py legislators.db congress-legislators
    - name: Set up Cloud Run
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '318.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        ./deploy.sh
